## <span style="color:purple"> Information extraction: named entities </span>

Named Entity Recognition (NER) is a subtask of information extraction that seeks to locate and classify elements in text into pre-defined categories such as the names of persons, organizations, locations.

EstNLTK has multiple NER models for Estonian. 
The traditional machine learning based model was created by [Tkachenko et al. (2013)](https://aclanthology.org/W13-2412/), and is available through `NerTagger` and `WordLevelNerTagger` components in EstNLTK. This model annotates names from categories `PER`, `LOC`, `ORG`.

First neural Bert-based models were created by [Kairit Sirts (2023)](https://openreview.net/pdf?id=4CTnlIc1rhw), and are usable via `EstBERTNERTagger` component in EstNLTK neural. 
There are 2 neural NER models: the first recognises names from the basic categories (`PER`, `LOC`, `ORG`), and the second recognises names from the extended set of categories: `PER`, `LOC`, `ORG`, `GPE`, `MONEY`, `PERCENT`, `PROD`, `TITLE`, `DATE`, `TIME`, `EVENT`. The first model is also usable via webservice (`NerWebTagger`). 

A Bert-based model has also been fine-tuned on the Estonian UD treebanks ([EDT](https://github.com/UniversalDependencies/UD_Estonian-EDT) and [EWT](https://github.com/UniversalDependencies/UD_Estonian-EWT)) by [Martin Kivisikk (2025)](https://thesis.cs.ut.ee/41345518-f5a0-471a-b3de-eddfa5d7073a). This model recognizes 8 types of entities: `PER`, `LOC`, `ORG`, `PROD`, `GEP` (geopolitical entity), `EVE` (event), `MUU` (misc) and `UNK` (unknown).

---

## The basic NER model (traditional ML)

The traditional machine learning based NER is distributed with the EstNLTK main package.

You can apply NER directly via default resolver:

In [1]:
from estnltk import Text

text = Text('Eesti president on Alar Karis. Eesti Energia on Eesti riigile kuuluv energiaettevõte.')

text.tag_layer('ner')

text.ner

Layer(name='ner', attributes=('nertag',), spans=SL[EnvelopingSpan(['Eesti'], [{'nertag': 'LOC'}]),
EnvelopingSpan(['Alar', 'Karis'], [{'nertag': 'PER'}]),
EnvelopingSpan(['Eesti', 'Energia'], [{'nertag': 'ORG'}]),
EnvelopingSpan(['Eesti', 'riigile'], [{'nertag': 'LOC'}])])

You can use `enclosing_text` to obtain exact strings corresponding to named entities:

In [2]:
# Get named entity strings
[named_entity.enclosing_text for named_entity in text.ner]

['Eesti', 'Alar Karis', 'Eesti Energia', 'Eesti riigile']

While NerTagger does not provide lemmatization of names, you can iterate over all words of each named entity, and you can get lemmas for these words from the `morph_analysis` layer:

In [3]:
# Get lemmas of the named entities
for named_entity in text.ner:
    for word in named_entity:
        print(word.text, word.lemma)
    print()

Eesti ['Eesti']

Alar ['Alar']
Karis ['Karis']

Eesti ['Eesti']
Energia ['energia']

Eesti ['Eesti']
riigile ['riik']

Note that lemmas are provided as a list due to ambiguities in the morph analysis layer.

## Usage as a tagger 

Next, we'll see how to use NerTagger as a separate tagger.

Loading the tagger:

In [4]:
from estnltk.taggers import NerTagger

nertagger = NerTagger()

Create a text object and add prerequisite layers

In [5]:
from estnltk import Text

In [6]:
text = Text('''Eesti Vabariik on riik Põhja-Euroopas. Eesti piirneb põhjas üle Soome lahe Soome Vabariigiga.''')
text = text.tag_layer(['sentences', 'morph_analysis'])

Add the NER layer to the text

In [7]:
nertagger.tag(text)

Text(text='Eesti Vabariik on riik Põhja-Euroopas. Eesti piirneb põhjas üle Soome lahe Soome Vabariigiga.')

The nertag attribute shows the category of each named entity, either "LOC" - location, "PER" - person or "ORG" - organization

In [8]:
text.ner

Layer(name='ner', attributes=('nertag',), spans=SL[EnvelopingSpan(['Eesti', 'Vabariik'], [{'nertag': 'LOC'}]),
EnvelopingSpan(['Põhja-Euroopas'], [{'nertag': 'LOC'}]),
EnvelopingSpan(['Eesti'], [{'nertag': 'LOC'}]),
EnvelopingSpan(['Soome', 'lahe'], [{'nertag': 'LOC'}]),
EnvelopingSpan(['Soome', 'Vabariigiga'], [{'nertag': 'LOC'}])])

For some use cases it might be better to have the output layer with a tag for each word. This can be used for visualizing or making manual changes to the layer.

In [9]:
from estnltk.taggers import WordLevelNerTagger

word_level_ner = WordLevelNerTagger()

In [10]:
word_level_ner.tag(text)

Text(text='Eesti Vabariik on riik Põhja-Euroopas. Eesti piirneb põhjas üle Soome lahe Soome Vabariigiga.')

Here, the tags are in IOB-format: B- prefix indicates that this token is the beginning of the named entity, I- prefix indicates that this token is inside the named entity. O shows that the token is outside named entities (not part of a named entity).

In [11]:
text.wordner

Layer(name='wordner', attributes=('nertag',), spans=SL[Span('Eesti', [{'nertag': 'B-LOC'}]),
Span('Vabariik', [{'nertag': 'I-LOC'}]),
Span('on', [{'nertag': 'O'}]),
Span('riik', [{'nertag': 'O'}]),
Span('Põhja-Euroopas', [{'nertag': 'B-LOC'}]),
Span('.', [{'nertag': 'O'}]),
Span('Eesti', [{'nertag': 'B-LOC'}]),
Span('piirneb', [{'nertag': 'O'}]),
Span('põhjas', [{'nertag': 'O'}]),
Span('üle', [{'nertag': 'O'}]),
Span('Soome', [{'nertag': 'B-LOC'}]),
Span('lahe', [{'nertag': 'I-LOC'}]),
Span('Soome', [{'nertag': 'B-LOC'}]),
Span('Vabariigiga', [{'nertag': 'I-LOC'}]),
Span('.', [{'nertag': 'O'}])])

---

## Neural NER models

### Running as a web tagger

Easiest way to use a neural NER is via TartuNLP's NER web service:

In [12]:
from estnltk import Text
from estnltk.web_taggers import NerWebTagger

ner_web_tagger = NerWebTagger()
ner_web_tagger

NerWebTagger(input_layers=('words',), output_layers=['webner'], output_layers_to_attributes={'webner': ['nertag']}, custom_words_layer=words, url=https://api.tartunlp.ai/bert/ner/v1, batch_size=4500)

In [13]:
text = Text('30. juunil 1632. aastal kinnitas Rootsi kuningas Gustav II Adolf oma allkirjaga '+\
"Nürnbergi all sõjalaagris Academia Dorpatensis'e asutamisüriku, mis lubab meie suurkooli ajalugu "+\
"sellest ajast alustada ja auväärseks lugeda.")
# Tag input layer
text = text.tag_layer('words')
# Tag named entities
ner_web_tagger.tag( text )
# check results
text['webner']

Layer(name='webner', attributes=('nertag',), spans=SL[EnvelopingSpan(['Rootsi'], [{'nertag': 'LOC'}]),
EnvelopingSpan(['Gustav', 'II', 'Adolf'], [{'nertag': 'PER'}]),
EnvelopingSpan(['Nürnbergi'], [{'nertag': 'LOC'}]),
EnvelopingSpan(['Academia', "Dorpatensis'e"], [{'nertag': 'ORG'}])])

Remarks:
* This webservice uses the ["estbertner"](https://huggingface.co/tartuNLP/EstBERT_NER) model which recognizes names from categories `PER`, `LOC` and `ORG`;
* Be aware that using this tagger means that the input data will be processed by the public TartuNLP API. The text will be uploaded and can be read by a third party;

### Local installation

*In order to use the neural NER models, please install [estnltk_neural](https://github.com/estnltk/estnltk/tree/main/estnltk_neural) (v1.7.2+).*

Before applying `EstBERTNERTagger`, you'll need to get the models. Models are not distributed with EstNLTK due to their large size, and need to be downloaded separately:

* If you create a new instance of `EstBERTNERTagger` and the models are missing, you'll be prompted with a question asking for a permission to download the "estbertner" model;
* Alternatively, you can pre-download models manually via `download` function:

```python
from estnltk import download
download("estbertner")
download("estbertner_v2")
download("estroberta_ud_ner_v1")
```

### Model estbertner

The model [estbertner_v1](https://huggingface.co/tartuNLP/EstBERT_NER) is an EstBERT based model fine-tuned for NER by [Kairit Sirts (2023)](https://openreview.net/pdf?id=4CTnlIc1rhw). It is the default model of `EstBERTNERTagger` and it recognizes three types of named entities: persons (`PER`), locations (`LOC`) and organizations (`ORG`):

In [14]:
from estnltk_neural.taggers import EstBERTNERTagger
neural_ner = EstBERTNERTagger()
neural_ner

Some weights of the model checkpoint at C:\Programmid\Miniconda3\envs\py312_devel\Lib\site-packages\estnltk\estnltk_resources\estbert\ner_model_hf_tartunlp_2022-05-06\ were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use cpu

EstBERTNERTagger(input_layers=('words',), output_layers=['estbertner'], output_layers_to_attributes={'estbertner': ['nertag']}, model_location=C:\Programmid\Miniconda3\envs\py312_devel\Lib\site-packages\estnltk\estnltk_reso ..., type: <class 'str'>, length: 127, nlp=<transformers.pipelines.token_classification.TokenClassificationPipeline object  ..., type: <class 'transformers.pipelines.token_classification.TokenClassificationPipeline'>, tokenizer=BertTokenizerFast(name_or_path='C:\Programmid\Miniconda3\envs\py312_devel\Lib\si ..., type: <class 'transformers.models.bert.tokenization_bert_fast.BertTokenizerFast'>, length: 50004, custom_words_layer=words, batch_size=1750, postfix_expand_suffixes=False, postfix_concat_same_type_entities=False, postfix_remove_infix_matches=False)

In [15]:
from estnltk import Text

text = Text('Eesti president on Alar Karis. Eesti Energia on Eesti riigile kuuluv energiaettevõte.')
# NER requires words layer
text.tag_layer('words')
# Add NER layer
neural_ner.tag(text)

text.estbertner

Layer(name='estbertner', attributes=('nertag',), spans=SL[EnvelopingSpan(['Eesti'], [{'nertag': 'LOC'}]),
EnvelopingSpan(['Alar', 'Karis'], [{'nertag': 'PER'}]),
EnvelopingSpan(['Eesti', 'Energia'], [{'nertag': 'ORG'}]),
EnvelopingSpan(['Eesti', 'riigile'], [{'nertag': 'LOC'}])])

### Model estbertner_v2

The model [estbertner_v2](https://huggingface.co/tartuNLP/EstBERT_NER_v2) is an EstBERT based model fine-tuned for NER by [Kairit Sirts (2023)](https://openreview.net/pdf?id=4CTnlIc1rhw).
The model recognizes 11 types of named entities: `PER`, `LOC`, `ORG`, `GPE`, `MONEY`, `PERCENT`, `PROD`, `TITLE`, `DATE`, `TIME`, `EVENT`. 
In order to use this model, you first need to download it via EstNLTK's downloader, and then pass it's location to `EstBERTNERTagger` via parameter `model_location`:

In [16]:
# Get the model
from estnltk import download, get_resource_paths
download("estbertner_v2")

Resource 'estbertner_v2_from_tartunlp_hf_2022-12-12' has already been downloaded.

True

In [17]:
# Initialize tagger with the model
model_location = get_resource_paths("estbertner_v2", only_latest=True)
neural_ner2 = EstBERTNERTagger(model_location=model_location, output_layer='estbertner2')

Device set to use cpu

In [18]:
from estnltk import Text

text = Text("Kaia Kanepi (WTA 57.) langes USA-s Charlestonis toimuval WTA 500 kategooria tenniseturniiril konkurentsist "+\
            "kaheksandikfinaalis, kaotades poolatarile Magda Linette'ile (WTA 64.) 3 : 6, 6 : 4, 2 : 6.")
# NER requires words layer
text.tag_layer('words')
# Add NER layer
neural_ner2.tag(text)

text.estbertner2

Layer(name='estbertner2', attributes=('nertag',), spans=SL[EnvelopingSpan(['Kaia', 'Kanepi'], [{'nertag': 'PER'}]),
EnvelopingSpan(['WTA'], [{'nertag': 'ORG'}]),
EnvelopingSpan(['USA-s'], [{'nertag': 'GPE'}]),
EnvelopingSpan(['Charlestonis'], [{'nertag': 'GPE'}]),
EnvelopingSpan(['WTA', '500', 'kategooria'], [{'nertag': 'EVENT'}]),
EnvelopingSpan(['poolatarile'], [{'nertag': 'TITLE'}]),
EnvelopingSpan(['Magda', "Linette'ile"], [{'nertag': 'PER'}]),
EnvelopingSpan(['WTA'], [{'nertag': 'ORG'}])])

### Model estroberta_ud_ner_v1

The model `estroberta_ud_ner_v1` is an Est-RoBERTa based model fine-tuned for NER on the Estonian UD treebanks ([EDT](https://github.com/UniversalDependencies/UD_Estonian-EDT) and [EWT](https://github.com/UniversalDependencies/UD_Estonian-EWT)) by [Martin Kivisikk (2025)](https://thesis.cs.ut.ee/41345518-f5a0-471a-b3de-eddfa5d7073a). 
This model recognizes 8 types of entities: `PER`, `LOC`, `ORG`, `PROD`, `GEP` (geopolitical entity), `EVE` (event), `MUU` (misc) and `UNK` (unknown).

In order to use this model, you first need to download it via EstNLTK's downloader, and then pass it's location to `EstBERTNERTagger` via parameter `model_location`:

In [19]:
# Get the model
from estnltk import download, get_resource_paths
download("estroberta_ud_ner_v1")

Resource 'estroberta_ud-ner_2025-04-25' has already been downloaded.

True

In [20]:
# Initialize tagger with the model
from estnltk_neural.taggers import EstBERTNERTagger
model_location_ud_ner = get_resource_paths("estroberta_ud_ner_v1", only_latest=True)
neural_ner_ud = EstBERTNERTagger(model_location=model_location_ud_ner, output_layer='estroberta_ud_ner')

Device set to use cpu

In [21]:
from estnltk import Text

text = Text("Kaia Kanepi (WTA 57.) langes USA-s Charlestonis toimuval WTA 500 kategooria tenniseturniiril konkurentsist "+\
            "kaheksandikfinaalis, kaotades poolatarile Magda Linette'ile (WTA 64.) 3 : 6, 6 : 4, 2 : 6.")
# NER requires words layer
text.tag_layer('words')
# Add NER layer
neural_ner_ud.tag(text)

text.estroberta_ud_ner

Layer(name='estroberta_ud_ner', attributes=('nertag',), spans=SL[EnvelopingSpan(['Kaia', 'Kanepi'], [{'nertag': 'PER'}]),
EnvelopingSpan(['USA-s'], [{'nertag': 'GEP'}]),
EnvelopingSpan(['Charlestonis'], [{'nertag': 'LOC'}]),
EnvelopingSpan(['WTA', '500', 'kategooria', 'tenniseturniiril'], [{'nertag': 'EVE'}]),
EnvelopingSpan(['Magda', "Linette'ile"], [{'nertag': 'PER'}])])

### Using hardware acceleration (GPU)

Use the parameter `device` to switch from CPU (default) to a GPU to speed up the processing, for example:

```python
from estnltk_neural.taggers import EstBERTNERTagger
estbertner_v1 = EstBERTNERTagger(device='cuda')  # use GPU
```

Note that this requires an environment where GPU is available. 
Under the hood, this corresponds to initializing transformers' [TokenClassificationPipeline](https://huggingface.co/docs/transformers/v4.57.1/en/main_classes/pipelines#transformers.TokenClassificationPipeline) with the corresponding `device` parameter. By default, no hardware acceleration is used.

### Tokenization of NE layers. Restoring Bert's tokenization

By default, detected named entities will envelop around EstNLTK's words layer. 
However, under the hood, Bert models use a different tokenization and the envelopment around words has been achieved heuristically. 
In many cases, Bert's tokenizer splits a word into multiple tokens (e.g. `'Charlestonis'` will become tokenized into `['Cha', 'rl', 'est', 'onis']`) and Bert's named entity labels may not cover all tokens of a word (e.g. frequently Estonian case endings will not be covered).
The heuristic checks for a minimal (one letter) overlap between a Bert token with a named entity label and a word: if the overlap exists, then the word will obtain corresponding named entity label. 
If there are multiple Bert tokens with named entity labels covering a word, then the word will obtain the label of the first Bert token.

If you want to get the original Bert NE output/tokenization, then use `custom_words_layer=None` to switch off the heuristic. 
As a result, the tagger will create 2 layers: the layer with the original Bert tokenization (`nertokens`), and the NE layer enveloping around the Bert tokenization layer.
Example:

In [22]:
# Switch off mapping NE-s to words layer
neural_ner3 = EstBERTNERTagger(model_location=model_location_ud_ner, output_layer='estbertner3', custom_words_layer=None)

Device set to use cpu

In [23]:
# Add NER layer
neural_ner3.tag(text)

# Examine NER results on the original Bert tokenization
text.estbertner3

Layer(name='estbertner3', attributes=('nertag',), spans=SL[EnvelopingSpan(['Kaia', ' Kanepi'], [{'nertag': 'PER'}]),
EnvelopingSpan([' USA'], [{'nertag': 'GEP'}]),
EnvelopingSpan(['-'], [{'nertag': 'GEP'}]),
EnvelopingSpan(['s'], [{'nertag': 'GEP'}]),
EnvelopingSpan([' Char'], [{'nertag': 'LOC'}]),
EnvelopingSpan(['lest'], [{'nertag': 'LOC'}]),
EnvelopingSpan(['onis'], [{'nertag': 'LOC'}]),
EnvelopingSpan([' WTA', ' 500', ' kategooria', ' tennise', 'turniiril'], [{'nertag': 'EVE'}]),
EnvelopingSpan([' Mag'], [{'nertag': 'PER'}]),
EnvelopingSpan(['da', ' Line', 'tte', "'", 'ile'], [{'nertag': 'PER'}])])

In [24]:
text.estbertner3.display()

In [25]:
# Examine the original Bert's tokenization
text.nertokens

Layer(name='nertokens', attributes=(), spans=SL[Span('Kaia', [{}]),
Span(' Kanepi', [{}]),
Span(' (', [{}]),
Span('W', [{}]),
Span('TA', [{}]),
Span(' 5', [{}]),
Span('7.', [{}]),
Span(')', [{}]),
Span(' langes', [{}]),
Span(' USA', [{}]),
Span('-', [{}]),
Span('s', [{}]),
Span(' Char', [{}]),
Span('lest', [{}]),
Span('onis', [{}]),
Span(' toimuval', [{}]),
Span(' WTA', [{}]),
Span(' 500', [{}]),
Span(' kategooria', [{}]),
Span(' tennise', [{}]),
Span('turniiril', [{}]),
Span(' konkurents', [{}]),
Span('ist', [{}]),
Span(' kaheksand', [{}]),
Span('ik', [{}]),
Span('finaalis', [{}]),
Span(',', [{}]),
Span(' kaotades', [{}]),
Span(' poola', [{}]),
Span('ta', [{}]),
Span('rile', [{}]),
Span(' Mag', [{}]),
Span('da', [{}]),
Span(' Line', [{}]),
Span('tte', [{}]),
Span("'", [{}]),
Span('ile', [{}]),
Span(' (', [{}]),
Span('W', [{}]),
Span('TA', [{}]),
Span(' 6', [{}]),
Span('4.', [{}]),
Span(')', [{}]),
Span(' 3', [{}]),
Span(' :', [{}]),
Span(' 6,', [{}]),
Span(' 6', [{}]),
Span(' :', [{}]),
Span(' 4,', [{}]),
Span(' 2', [{}]),
Span(' :', [{}]),
Span(' 6.', [{}])])

---