# EstNLTK's table display

EstNLTK's data structures (e.g. `Text`, `Layer`, `Annotation` objects) and central components (e.g. `Tagger` and `Retagger` objects) have table representations, which can be seen in [Jupyter Notebook](https://jupyter.org/) or other similar interactive programming environments that render HTML. 

Table representations allow to:

* browse text and layer contents: see annotated text spans, corresponding tags, attribute values and metadata;
* examine layer/annotation structure and statistics;
* inspect tagger's configuration: which models and settings are used;

## I. Basics

By default, Jupyter Notebook shows an HTML representation of the last item/object in the code cell:

In [1]:
from estnltk import Text
text = Text('Ekspert on inimene, kes on teinud kõik võimalikud vead ühel kitsal erialal.').tag_layer('morph_analysis')
text

Text(text='Ekspert on inimene, kes on teinud kõik võimalikud vead ühel kitsal erialal.')

You can use Jupyter Notebook's built-in function `display()` to render a table representation of EstNLTK's object at any cell location, for example:

In [2]:
# Render table representations of 3 first words in morph_analysis
display( text['morph_analysis'][0] )
display( text['morph_analysis'][1] )
display( text['morph_analysis'][2] )

Span('Ekspert', [{'normalized_text': 'Ekspert', 'lemma': 'ekspert', 'root': 'ekspert', 'root_tokens': ['ekspert'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}])

Span('on', [{'normalized_text': 'on', 'lemma': 'olema', 'root': 'ole', 'root_tokens': ['ole'], 'ending': '0', 'clitic': '', 'form': 'b', 'partofspeech': 'V'}, {'normalized_text': 'on', 'lemma': 'olema', 'root': 'ole', 'root_tokens': ['ole'], 'ending': '0', 'clitic': '', 'form': 'vad', 'partofspeech': 'V'}])

Span('inimene', [{'normalized_text': 'inimene', 'lemma': 'inimene', 'root': 'inimene', 'root_tokens': ['inimene'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}])

Function `display()` can be useful if you need to render EstNLTK's tables inside a loop.

_How to display annotations within the whole text, e.g. highlight annotated text snippets?_ See the tutorial about the [span visualisation](B_span_visualisation.ipynb).

---

## II. Table display options

EstNLTK's table display has several configurable options.

#### A. Maximum length of text in the HTML representation
#### (how to see long sentences at their full length) 

The maxium length of a string in EstNLTK's HTML output is limited to 100 characters. If data exceeds that length, then it will be truncated and information about data type and length will be added at the end of the string. 
Example:

In [3]:
from estnltk import Text
# Create text with long sentences
text = Text('''Seetõttu väljenduvad teadlased lühidalt ja abstraktselt; nende väljendusviis on mõistetav teistele 
eriteadlastele, kuid asjasse pühendamatuile võib see arusaamatuks jääda. Küllap seetõttu ongi meie kooliõpikud ülemäära 
rasked ja sobimatud iseseisvaks tööks. Kui autor pöördub vähem ettevalmistatud lugejate poole, siis peaks ta teadlikult 
arvestama mõistetava teksti reegleid.''')
text.tag_layer('sentences')
# See results
text['sentences']

Layer(name='sentences', attributes=(), spans=SL[EnvelopingSpan(['Seetõttu', 'väljenduvad', 'teadlased', 'lühidalt', 'ja', 'abstraktselt', ';', 'nende', 'väljendusviis', 'on', 'mõistetav', 'teistele', 'eriteadlastele', ',', 'kuid', 'asjasse', 'pühendamatuile', 'võib', 'see', 'arusaamatuks', 'jääda', '.'], [{}]),
EnvelopingSpan(['Küllap', 'seetõttu', 'ongi', 'meie', 'kooliõpikud', 'ülemäära', 'rasked', 'ja', 'sobimatud', 'iseseisvaks', 'tööks', '.'], [{}]),
EnvelopingSpan(['Kui', 'autor', 'pöördub', 'vähem', 'ettevalmistatud', 'lugejate', 'poole', ',', 'siis', 'peaks', 'ta', 'teadlikult', 'arvestama', 'mõistetava', 'teksti', 'reegleid', '.'], [{}])])

You can change the setting `OUTPUT_CONFIG['html_str_max_len']` to allow displaying longer strings:

In [4]:
# Change setting: display at least 300 characters in html field output 
# (in order to see 'sentences' at the full length)
from estnltk_core.common import OUTPUT_CONFIG
default_html_str_max_len = OUTPUT_CONFIG['html_str_max_len']
OUTPUT_CONFIG['html_str_max_len'] = 300

In [5]:
# See results
text['sentences']

Layer(name='sentences', attributes=(), spans=SL[EnvelopingSpan(['Seetõttu', 'väljenduvad', 'teadlased', 'lühidalt', 'ja', 'abstraktselt', ';', 'nende', 'väljendusviis', 'on', 'mõistetav', 'teistele', 'eriteadlastele', ',', 'kuid', 'asjasse', 'pühendamatuile', 'võib', 'see', 'arusaamatuks', 'jääda', '.'], [{}]),
EnvelopingSpan(['Küllap', 'seetõttu', 'ongi', 'meie', 'kooliõpikud', 'ülemäära', 'rasked', 'ja', 'sobimatud', 'iseseisvaks', 'tööks', '.'], [{}]),
EnvelopingSpan(['Kui', 'autor', 'pöördub', 'vähem', 'ettevalmistatud', 'lugejate', 'poole', ',', 'siis', 'peaks', 'ta', 'teadlikult', 'arvestama', 'mõistetava', 'teksti', 'reegleid', '.'], [{}])])

In [6]:
# Reverse setting
OUTPUT_CONFIG['html_str_max_len'] = default_html_str_max_len

#### B. Show start and end indexes of spans

By default, layer's table representation shows annotated texts (spans), but does not show exact start and end indexes of the spans.
You can set the instance variable `print_start_end` to display also start and end indexes:

In [7]:
from estnltk import Text
text = Text('Ekspert on inimene, kes on teinud kõik võimalikud vead ühel kitsal erialal.').tag_layer('words')
# Switch on printing start and end indexes
text['words'].print_start_end = True

In [8]:
text['words']

Layer(name='words', attributes=('normalized_form',), spans=SL[Span('Ekspert', [{'normalized_form': None}]),
Span('on', [{'normalized_form': None}]),
Span('inimene', [{'normalized_form': None}]),
Span(',', [{'normalized_form': None}]),
Span('kes', [{'normalized_form': None}]),
Span('on', [{'normalized_form': None}]),
Span('teinud', [{'normalized_form': None}]),
Span('kõik', [{'normalized_form': None}]),
Span('võimalikud', [{'normalized_form': None}]),
Span('vead', [{'normalized_form': None}]),
Span('ühel', [{'normalized_form': None}]),
Span('kitsal', [{'normalized_form': None}]),
Span('erialal', [{'normalized_form': None}]),
Span('.', [{'normalized_form': None}])])

Note that the effect of `print_start_end` is local: it affects only the current layer, not other layers.

In [9]:
# Switch off printing start and end indexes
text['words'].print_start_end = False

---